/* registrazione.js v3 — traduzione IN LOCO (5.177) + intro + wallet + flusso pioniere. */
(function () {
  var T = {
    it: { h1: 'I pionieri.', nota: 'Dopo l\u0027invio riceverai una mail di conferma e un SMS; poi entri — le funzioni si liberano quando tutto è pronto.', lead: 'Stiamo mettendo a punto qualcosa che il mondo non ha mai visto. Entra prima degli altri.', accesso: 'L\u0027accesso.', vetrina: 'In questa fase di costruzione l\u0027accesso richiede la registrazione: dopo l\u0027ingresso vedi la vetrina di tutte le aste pvp.giustizia — iCARe ti accompagna nella navigazione.', mille: 'I primi 1.000 iscritti: il primo anno di abbonamento è gratuito (pagherai solo la commissione iShop e la success fee come previsto).', piani: 'Gli abbonamenti: Gold con vincolo 12 mesi €59,90/mese · Gold mensile senza vincolo €69,90/mese.', world: 'iCARe World: per over 70 e persone con disabilità certificata (L. 104/92), sconto del 50% e assistenza umana prioritaria.', reg: 'Registrati.', nome: 'Nome e cognome', email: 'Email', cel: 'Cellulare (per la conferma SMS)', eta: 'Fascia d\u0027età', citta: 'La tua città', gusti: 'I tuoi interessi (i gusti della Community)', g1: 'Aste giudiziarie', g2: 'Buy Now', g3: 'iHouse modulare', g4: 'Arredo e iShop', g5: 'Investimento', g6: 'Prima casa', p1: 'Acconsento al trattamento dei dati personali (GDPR).', p2: 'Voglio ricevere gli aggiornamenti della Rivoluzione iUmana.', btn: 'Diventa pioniere', wallet: 'Registrati con Google, Apple o email: il tuo wallet (Apple Pay / Google Pay) si collega al checkout — noi prendiamo dal wallet solo ciò che serve.', grazie: '✅ Benvenuto tra i pionieri. Conferma la mail che si è aperta.' },
    en: { h1: 'The pioneers.', nota: 'After submitting, you receive a confirmation email and an SMS; then you enter — features unlock as everything becomes ready.', lead: 'We are fine-tuning something the world has never seen. Enter before everyone else.', accesso: 'Access.', vetrina: 'In this construction phase access requires registration: once inside you see the showcase of all pvp.giustizia auctions — iCARe guides your navigation.', mille: 'The first 1,000 members: the first year of subscription is free (you pay only the iShop commission and the success fee).', piani: 'Plans: Gold 12-month €59.90/month · Gold monthly no lock-in €69.90/month.', world: 'iCARe World: for over-70 and certified disability (L. 104/92), 50% discount and priority human assistance.', reg: 'Register.', nome: 'Full name', email: 'Email', cel: 'Mobile (for SMS confirmation)', eta: 'Age range', citta: 'Your city', gusti: 'Your interests (the tastes of the Community)', g1: 'Judicial auctions', g2: 'Buy Now', g3: 'Modular iHouse', g4: 'Furniture and iShop', g5: 'Investment', g6: 'First home', p1: 'I consent to personal data processing (GDPR).', p2: 'I want updates on the iUmana Revolution.', btn: 'Become a pioneer', wallet: 'Register with Google, Apple or email: your wallet (Apple Pay / Google Pay) connects at checkout — we take from the wallet only what is needed.', grazie: '✅ Welcome, pioneer. Confirm the email that just opened.' },
    de: { h1: 'Die Pioniere.', nota: 'Nach dem Absenden erhältst du eine Bestätigungs-E-Mail und eine SMS; dann kommst du hinein — die Funktionen werden freigeschaltet, sobald alles bereit ist.', lead: 'Wir feilen an etwas, das die Welt noch nie gesehen hat. Komm vor allen anderen.', accesso: 'Zugang.', vetrina: 'In dieser Aufbauphase erfordert der Zugang eine Registrierung: danach siehst du die Vitrine aller pvp.giustizia-Auktionen — iCARe begleitet deine Navigation.', mille: 'Die ersten 1.000 Mitglieder: das erste Jahr ist kostenlos (nur iShop-Provision und Erfolgsgebühr).', piani: 'Pläne: Gold 12 Monate 59,90 €/Monat · Gold monatlich 69,90 €/Monat.', world: 'iCARe World: für über 70-Jährige und anerkannte Behinderung (L. 104/92) 50 % Rabatt und vorrangige menschliche Hilfe.', reg: 'Registrieren.', nome: 'Vor- und Nachname', email: 'E-Mail', cel: 'Mobil (SMS-Bestätigung)', eta: 'Altersgruppe', citta: 'Deine Stadt', gusti: 'Deine Interessen', g1: 'Zwangsversteigerungen', g2: 'Buy Now', g3: 'Modulares iHouse', g4: 'Möbel und iShop', g5: 'Investition', g6: 'Erstes Haus', p1: 'Ich stimme der Datenverarbeitung zu (DSGVO).', p2: 'Ich möchte Updates zur iUmana-Revolution.', btn: 'Pionier werden', wallet: 'Registriere dich mit Google, Apple oder E-Mail: dein Wallet (Apple Pay / Google Pay) verbindet sich beim Checkout.', grazie: '✅ Willkommen, Pionier. Bestätige die geöffnete E-Mail.' },
    es: { h1: 'Los pioneros.', nota: 'Tras enviar recibirás un email de confirmación y un SMS; luego entras — las funciones se desbloquean cuando todo esté listo.', lead: 'Estamos afinando algo que el mundo nunca ha visto. Entra antes que los demás.', accesso: 'Acceso.', vetrina: 'En esta fase de construcción el acceso requiere registro: dentro verás el escaparate de todas las subastas pvp.giustizia — iCARe te guía.', mille: 'Los primeros 1.000 inscritos: el primer año de suscripción es gratuito (solo comisión iShop y success fee).', piani: 'Planes: Gold 12 meses 59,90 €/mes · Gold mensual 69,90 €/mes.', world: 'iCARe World: para mayores de 70 y discapacidad certificada (L. 104/92), 50% de descuento y asistencia humana prioritaria.', reg: 'Regístrate.', nome: 'Nombre completo', email: 'Email', cel: 'Móvil (confirmación SMS)', eta: 'Franja de edad', citta: 'Tu ciudad', gusti: 'Tus intereses', g1: 'Subastas judiciales', g2: 'Buy Now', g3: 'iHouse modular', g4: 'Muebles e iShop', g5: 'Inversión', g6: 'Primera vivienda', p1: 'Consiento el tratamiento de datos (RGPD).', p2: 'Quiero novedades de la Revolución iUmana.', btn: 'Hazte pionero', wallet: 'Regístrate con Google, Apple o email: tu wallet (Apple Pay / Google Pay) se conecta al checkout.', grazie: '✅ Bienvenido, pionero. Confirma el email que se ha abierto.' },
    fr: { h1: 'Les pionniers.', nota: 'Après l\u0027envoi tu reçois un email de confirmation et un SMS ; ensuite tu entres — les fonctions se débloquent quand tout est prêt.', lead: 'Nous peaufinons quelque chose que le monde n\u0027a jamais vu. Entre avant tout le monde.', accesso: 'Accès.', vetrina: 'Dans cette phase de construction l\u0027accès exige l\u0027inscription : ensuite tu vois la vitrine de toutes les enchères pvp.giustizia — iCARe te guide.', mille: 'Les 1.000 premiers inscrits : la première année est gratuite (seulement commission iShop et success fee).', piani: 'Formules : Gold 12 mois 59,90 €/mois · Gold mensuel 69,90 €/mois.', world: 'iCARe World : pour les plus de 70 ans et handicap certifié (L. 104/92), −50 % et assistance humaine prioritaire.', reg: 'S\u0027inscrire.', nome: 'Nom complet', email: 'Email', cel: 'Mobile (confirmation SMS)', eta: 'Tranche d\u0027âge', citta: 'Ta ville', gusti: 'Tes intérêts', g1: 'Enchères judiciaires', g2: 'Buy Now', g3: 'iHouse modulaire', g4: 'Meubles et iShop', g5: 'Investissement', g6: 'Première maison', p1: 'Je consens au traitement des données (RGPD).', p2: 'Je veux les actualités de la Révolution iUmana.', btn: 'Devenir pionnier', wallet: 'Inscris-toi avec Google, Apple ou email : ton wallet (Apple Pay / Google Pay) se connecte au checkout.', grazie: '✅ Bienvenue, pionnier. Confirme l\u0027email qui vient de s\u0027ouvrir.' },
    ru: { h1: 'Пионеры.', lead: 'Мы оттачиваем то, чего мир ещё не видел. Войди раньше всех.', accesso: 'Доступ.', vetrina: 'На этапе строительства нужна регистрация: внутри — витрина всех аукционов pvp.giustizia, iCARe ведёт тебя.', mille: 'Первые 1.000: первый год бесплатно (только комиссия iShop и success fee).', piani: 'Тарифы: Gold 12 мес. €59,90/мес · Gold помесячно €69,90/мес.', world: 'iCARe World: старше 70 и инвалидность (L. 104/92) — скидка 50% и приоритетная помощь человека.', reg: 'Регистрация.', nome: 'Имя и фамилия', email: 'Email', cel: 'Телефон (СМС)', eta: 'Возраст', citta: 'Ваш город', gusti: 'Ваши интересы', g1: 'Судебные аукционы', g2: 'Buy Now', g3: 'Модульный iHouse', g4: 'Мебель и iShop', g5: 'Инвестиции', g6: 'Первое жильё', p1: 'Согласен на обработку данных (GDPR).', p2: 'Хочу новости Революции iUmana.', btn: 'Стать пионером', wallet: 'Регистрация через Google, Apple или email: кошелёк (Apple Pay / Google Pay) подключается на checkout.', grazie: '✅ Добро пожаловать, пионер. Подтвердите открывшееся письмо.' },
    ja: { h1: 'パイオニアたち。', lead: '世界がまだ見たことのないものを磨いています。誰よりも先に入ってください。', accesso: 'アクセス。', vetrina: '構築段階では登録が必要です：入るとpvp.giustiziaの全オークションのショーケースが見えます — iCAReが案内します。', mille: '最初の1,000名：初年度無料（iShop手数料と成功報酬のみ）。', piani: 'プラン：Gold 12ヶ月 €59.90/月 · Gold 月額 €69.90/月。', world: 'iCARe World：70歳以上・認定障害（L. 104/92）は50%割引と優先サポート。', reg: '登録。', nome: '氏名', email: 'メール', cel: '携帯（SMS確認）', eta: '年齢層', citta: 'あなたの街', gusti: 'あなたの関心', g1: '裁判所オークション', g2: 'Buy Now', g3: 'モジュールiHouse', g4: '家具とiShop', g5: '投資', g6: '最初の家', p1: 'データ処理に同意します（GDPR）。', p2: 'iUmana革命の更新を受け取りたい。', btn: 'パイオニアになる', wallet: 'Google・Apple・メールで登録：ウォレット（Apple Pay / Google Pay）がチェックアウトに接続されます。', grazie: '✅ ようこそ、パイオニア。開いたメールを確認してください。' },
    ar: { h1: 'الروّاد.', lead: 'نصقل شيئاً لم يره العالم من قبل. ادخل قبل الجميع.', accesso: 'الدخول.', vetrina: 'في مرحلة البناء يتطلب الدخول التسجيل: بالداخل ترى واجهة جميع مزادات pvp.giustizia — iCARe يرشدك.', mille: 'أول 1.000 مشترك: السنة الأولى مجانية (فقط عمولة iShop ورسوم النجاح).', piani: 'الباقات: Gold لمدة 12 شهراً €59.90/شهر · Gold شهري €69.90/شهر.', world: 'iCARe World: لمن فوق 70 عاماً وذوي الإعاقة المعتمدة (L. 104/92) خصم 50% ومساعدة إنسانية ذات أولوية.', reg: 'التسجيل.', nome: 'الاسم الكامل', email: 'البريد الإلكتروني', cel: 'الجوال (تأكيد SMS)', eta: 'الفئة العمرية', citta: 'مدينتك', gusti: 'اهتماماتك', g1: 'المزادات القضائية', g2: 'Buy Now', g3: 'iHouse المعياري', g4: 'الأثاث و iShop', g5: 'الاستثمار', g6: 'المنزل الأول', p1: 'أوافق على معالجة البيانات (GDPR).', p2: 'أريد تحديثات ثورة iUmana.', btn: 'كن رائداً', wallet: 'سجّل عبر Google أو Apple أو البريد: محفظتك (Apple Pay / Google Pay) تتصل عند الدفع.', grazie: '✅ مرحباً أيها الرائد. أكّد البريد الذي فُتح.' },
    hi: { h1: 'पायनियर।', lead: 'हम कुछ ऐसा बना रहे हैं जो दुनिया ने कभी नहीं देखा। सबसे पहले प्रवेश करें।', accesso: 'पहुँच।', vetrina: 'निर्माण चरण में पंजीकरण ज़रूरी है: अंदर pvp.giustizia की सभी नीलामियों की झलक — iCARe मार्गदर्शन करता है।', mille: 'पहले 1.000 सदस्य: पहला साल मुफ़्त (केवल iShop कमीशन और सफलता शुल्क)।', piani: 'प्लान: Gold 12 महीने €59.90/माह · Gold मासिक €69.90/माह।', world: 'iCARe World: 70+ और प्रमाणित विकलांगता (L. 104/92) के लिए 50% छूट और प्राथमिक मानव सहायता।', reg: 'पंजीकरण।', nome: 'पूरा नाम', email: 'ईमेल', cel: 'मोबाइल (SMS पुष्टि)', eta: 'आयु वर्ग', citta: 'आपका शहर', gusti: 'आपकी रुचियाँ', g1: 'न्यायिक नीलामी', g2: 'Buy Now', g3: 'मॉड्यूलर iHouse', g4: 'फर्नीचर और iShop', g5: 'निवेश', g6: 'पहला घर', p1: 'मैं डेटा प्रोसेसिंग के लिए सहमत हूँ (GDPR)।', p2: 'मुझे iUmana क्रांति के अपडेट चाहिए।', btn: 'पायनियर बनें', wallet: 'Google, Apple या ईमेल से पंजीकरण: वॉलेट (Apple Pay / Google Pay) चेकआउट पर जुड़ता है।', grazie: '✅ स्वागत है, पायनियर। खुले ईमेल की पुष्टि करें।' },
    ko: { h1: '개척자들.', lead: '세상이 본 적 없는 것을 다듬고 있습니다. 누구보다 먼저 들어오세요.', accesso: '접근.', vetrina: '구축 단계에서는 등록이 필요합니다: 안에 들어오면 pvp.giustizia의 모든 경매 쇼케이스 — iCARe가 안내합니다.', mille: '최초 1,000명: 첫해 무료 (iShop 수수료와 성공 수수료만).', piani: '요금제: Gold 12개월 €59.90/월 · Gold 월간 €69.90/월.', world: 'iCARe World: 70세 이상 및 장애 인증(L. 104/92) 50% 할인과 우선 지원.', reg: '등록.', nome: '성명', email: '이메일', cel: '휴대폰(SMS 확인)', eta: '연령대', citta: '당신의 도시', gusti: '당신의 관심사', g1: '법원 경매', g2: 'Buy Now', g3: '모듈형 iHouse', g4: '가구와 iShop', g5: '투자', g6: '첫 집', p1: '데이터 처리에 동의합니다(GDPR).', p2: 'iUmana 혁명 소식을 받고 싶습니다.', btn: '개척자가 되다', wallet: 'Google, Apple 또는 이메일로 등록: 월렛(Apple Pay / Google Pay)이 결제에 연결됩니다.', grazie: '✅ 환영합니다, 개척자님. 열린 이메일을 확인하세요.' },
    zh: { h1: '先驱者。', lead: '我们正在打磨世界从未见过的东西。比别人更早进入。', accesso: '访问。', vetrina: '建设阶段需要注册：进入后可见 pvp.giustizia 全部拍卖橱窗 — iCARe 为你导航。', mille: '前 1,000 名注册者：第一年免费（仅 iShop 佣金和成功费）。', piani: '套餐：Gold 12个月 €59.90/月 · Gold 月付 €69.90/月。', world: 'iCARe World：70岁以上及认证残疾（L. 104/92）享 50% 折扣和优先人工协助。', reg: '注册。', nome: '姓名', email: '邮箱', cel: '手机（短信确认）', eta: '年龄段', citta: '你的城市', gusti: '你的兴趣', g1: '司法拍卖', g2: 'Buy Now', g3: '模块化 iHouse', g4: '家具与 iShop', g5: '投资', g6: '第一套房', p1: '我同意数据处理（GDPR）。', p2: '我想接收 iUmana 革命更新。', btn: '成为先驱者', wallet: '用 Google、Apple 或邮箱注册：钱包（Apple Pay / Google Pay）在结账时连接。', grazie: '✅ 欢迎，先驱者。请确认刚打开的邮件。' },
    pt: { h1: 'Os pioneiros.', lead: 'Estamos a afinar algo que o mundo nunca viu. Entra antes de todos.', accesso: 'Acesso.', vetrina: 'Nesta fase de construção o acesso exige registo: dentro vês a montra de todos os leilões pvp.giustizia — o iCARe guia-te.', mille: 'Os primeiros 1.000: o primeiro ano é gratuito (só comissão iShop e success fee).', piani: 'Planos: Gold 12 meses €59,90/mês · Gold mensal €69,90/mês.', world: 'iCARe World: para maiores de 70 e deficiência certificada (L. 104/92), 50% de desconto e assistência humana prioritária.', reg: 'Registar.', nome: 'Nome completo', email: 'Email', cel: 'Telemóvel (confirmação SMS)', eta: 'Faixa etária', citta: 'A tua cidade', gusti: 'Os teus interesses', g1: 'Leilões judiciais', g2: 'Buy Now', g3: 'iHouse modular', g4: 'Mobiliário e iShop', g5: 'Investimento', g6: 'Primeira casa', p1: 'Consinto no tratamento de dados (RGPD).', p2: 'Quero novidades da Revolução iUmana.', btn: 'Tornar-me pioneiro', wallet: 'Regista-te com Google, Apple ou email: a tua wallet (Apple Pay / Google Pay) liga-se no checkout.', grazie: '✅ Bem-vindo, pioneiro. Confirma o email que abriu.' },
    pl: { h1: 'Pionierzy.', lead: 'Dopracowujemy coś, czego świat jeszcze nie widział. Wejdź przed wszystkimi.', accesso: 'Dostęp.', vetrina: 'W fazie budowy dostęp wymaga rejestracji: w środku widzisz witrynę wszystkich aukcji pvp.giustizia — iCARe prowadzi.', mille: 'Pierwszych 1.000: pierwszy rok gratis (tylko prowizja iShop i success fee).', piani: 'Plany: Gold 12 mies. €59,90/mies. · Gold miesięczny €69,90/mies.', world: 'iCARe World: dla 70+ i orzeczonej niepełnosprawności (L. 104/92) −50% i priorytetowa pomoc.', reg: 'Rejestracja.', nome: 'Imię i nazwisko', email: 'Email', cel: 'Telefon (potwierdzenie SMS)', eta: 'Wiek', citta: 'Twoje miasto', gusti: 'Twoje zainteresowania', g1: 'Licytacje komornicze', g2: 'Buy Now', g3: 'Modułowy iHouse', g4: 'Meble i iShop', g5: 'Inwestycja', g6: 'Pierwsze mieszkanie', p1: 'Zgadzam się na przetwarzanie danych (RODO).', p2: 'Chcę aktualizacje Rewolucji iUmana.', btn: 'Zostań pionierem', wallet: 'Zarejestruj się przez Google, Apple lub email: portfel (Apple Pay / Google Pay) łączy się przy płatności.', grazie: '✅ Witaj, pionierze. Potwierdź otwarty email.' },
    uk: { h1: 'Піонери.', lead: 'Ми відточуємо те, чого світ ще не бачив. Заходь раніше за всіх.', accesso: 'Доступ.', vetrina: 'На етапі будівництва потрібна реєстрація: всередині — вітрина всіх аукціонів pvp.giustizia, iCARe веде тебе.', mille: 'Перші 1.000: перший рік безкоштовно (лише комісія iShop і success fee).', piani: 'Тарифи: Gold 12 міс. €59,90/міс · Gold щомісяця €69,90/міс.', world: 'iCARe World: для 70+ і людей з інвалідністю (L. 104/92) знижка 50% і пріоритетна допомога.', reg: 'Реєстрація.', nome: 'Ім\u0027я та прізвище', email: 'Email', cel: 'Телефон (SMS)', eta: 'Вік', citta: 'Твоє місто', gusti: 'Твої інтереси', g1: 'Судові аукціони', g2: 'Buy Now', g3: 'Модульний iHouse', g4: 'Меблі та iShop', g5: 'Інвестиції', g6: 'Перше житло', p1: 'Згоден на обробку даних (GDPR).', p2: 'Хочу новини Революції iUmana.', btn: 'Стати піонером', wallet: 'Реєстрація через Google, Apple або email: гаманець (Apple Pay / Google Pay) підключається на checkout.', grazie: '✅ Ласкаво просимо, піонере. Підтвердь відкритий лист.' },
    vi: { h1: 'Những người tiên phong.', lead: 'Chúng tôi đang hoàn thiện điều thế giới chưa từng thấy. Vào trước tất cả.', accesso: 'Truy cập.', vetrina: 'Giai đoạn xây dựng cần đăng ký: bên trong bạn thấy tủ trưng bày mọi phiên đấu giá pvp.giustizia — iCARe dẫn đường.', mille: '1.000 người đầu tiên: năm đầu miễn phí (chỉ hoa hồng iShop và phí thành công).', piani: 'Gói: Gold 12 tháng €59,90/tháng · Gold hàng tháng €69,90/tháng.', world: 'iCARe World: trên 70 tuổi và khuyết tật có chứng nhận (L. 104/92) giảm 50% và hỗ trợ ưu tiên.', reg: 'Đăng ký.', nome: 'Họ tên', email: 'Email', cel: 'Di động (xác nhận SMS)', eta: 'Độ tuổi', citta: 'Thành phố của bạn', gusti: 'Sở thích của bạn', g1: 'Đấu giá tư pháp', g2: 'Buy Now', g3: 'iHouse mô-đun', g4: 'Nội thất và iShop', g5: 'Đầu tư', g6: 'Nhà đầu tiên', p1: 'Tôi đồng ý xử lý dữ liệu (GDPR).', p2: 'Tôi muốn nhận cập nhật Cách mạng iUmana.', btn: 'Trở thành tiên phong', wallet: 'Đăng ký bằng Google, Apple hoặc email: ví (Apple Pay / Google Pay) kết nối khi thanh toán.', grazie: '✅ Chào mừng, người tiên phong. Xác nhận email vừa mở.' },
    ro: { h1: 'Pionierii.', lead: 'Cizelăm ceva ce lumea nu a mai văzut. Intră înaintea tuturor.', accesso: 'Acces.', vetrina: 'În faza de construcție accesul cere înregistrare: înăuntru vezi vitrina tuturor licitațiilor pvp.giustizia — iCARe te ghidează.', mille: 'Primii 1.000: primul an gratuit (doar comision iShop și success fee).', piani: 'Planuri: Gold 12 luni €59,90/lună · Gold lunar €69,90/lună.', world: 'iCARe World: pentru peste 70 de ani și handicap certificat (L. 104/92), −50% și asistență umană prioritară.', reg: 'Înregistrare.', nome: 'Nume complet', email: 'Email', cel: 'Mobil (confirmare SMS)', eta: 'Vârstă', citta: 'Orașul tău', gusti: 'Interesele tale', g1: 'Licitații judiciare', g2: 'Buy Now', g3: 'iHouse modular', g4: 'Mobilier și iShop', g5: 'Investiție', g6: 'Prima casă', p1: 'Consimt la prelucrarea datelor (GDPR).', p2: 'Vreau noutăți despre Revoluția iUmana.', btn: 'Devino pionier', wallet: 'Înregistrare cu Google, Apple sau email: portofelul (Apple Pay / Google Pay) se conectează la checkout.', grazie: '✅ Bine ai venit, pioniere. Confirmă emailul deschis.' },
    tl: { h1: 'Ang mga pioneer.', lead: 'Pinipino namin ang isang bagay na hindi pa nakikita ng mundo. Pumasok bago ang lahat.', accesso: 'Pag-access.', vetrina: 'Sa yugto ng konstruksyon kailangan ang pagpaparehistro: sa loob makikita mo ang showcase ng lahat ng pvp.giustizia auctions — ginagabayan ka ng iCARe.', mille: 'Unang 1.000: libre ang unang taon (iShop commission at success fee lang).', piani: 'Plano: Gold 12 buwan €59.90/buwan · Gold buwanan €69.90/buwan.', world: 'iCARe World: para sa 70+ at sertipikadong kapansanan (L. 104/92), 50% bawas at priyoridad na tulong.', reg: 'Magparehistro.', nome: 'Buong pangalan', email: 'Email', cel: 'Mobile (SMS kumpirmasyon)', eta: 'Edad', citta: 'Iyong lungsod', gusti: 'Iyong mga interes', g1: 'Judicial auctions', g2: 'Buy Now', g3: 'Modular iHouse', g4: 'Muwebles at iShop', g5: 'Investasyon', g6: 'Unang bahay', p1: 'Sumasang-ayon ako sa pagpoproseso ng datos (GDPR).', p2: 'Gusto ko ng updates sa iUmana Revolution.', btn: 'Maging pioneer', wallet: 'Magrehistro gamit ang Google, Apple o email: kumokonekta ang wallet (Apple Pay / Google Pay) sa checkout.', grazie: '✅ Maligayang pagdating, pioneer. Kumpirmahin ang binuksang email.' },
    el: { h1: 'Οι πρωτοπόροι.', lead: 'Λειαίνουμε κάτι που ο κόσμος δεν έχει ξαναδεί. Μπες πριν από όλους.', accesso: 'Πρόσβαση.', vetrina: 'Στη φάση κατασκευής απαιτείται εγγραφή: μέσα βλέπεις τη βιτρίνα όλων των πλειστηριασμών pvp.giustizia — σε οδηγεί η iCARe.', mille: 'Οι πρώτοι 1.000: ο πρώτος χρόνος δωρεάν (μόνο προμήθεια iShop και success fee).', piani: 'Πλάνα: Gold 12 μήνες €59,90/μήνα · Gold μηνιαίο €69,90/μήνα.', world: 'iCARe World: για 70+ και πιστοποιημένη αναπηρία (L. 104/92), −50% και προτεραιότητα ανθρώπινης βοήθειας.', reg: 'Εγγραφή.', nome: 'Ονοματεπώνυμο', email: 'Email', cel: 'Κινητό (επιβεβαίωση SMS)', eta: 'Ηλικία', citta: 'Η πόλη σου', gusti: 'Τα ενδιαφέροντά σου', g1: 'Δικαστικοί πλειστηριασμοί', g2: 'Buy Now', g3: 'Σπονδυλωτό iHouse', g4: 'Έπιπλα και iShop', g5: 'Επένδυση', g6: 'Πρώτο σπίτι', p1: 'Συναινώ στην επεξεργασία δεδομένων (GDPR).', p2: 'Θέλω νέα της Επανάστασης iUmana.', btn: 'Γίνε πρωτοπόρος', wallet: 'Εγγραφή με Google, Apple ή email: το πορτοφόλι (Apple Pay / Google Pay) συνδέεται στο checkout.', grazie: '✅ Καλώς ήρθες, πρωτοπόρε. Επιβεβαίωσε το email που άνοιξε.' },
    nl: { h1: 'De pioniers.', lead: 'We verfijnen iets wat de wereld nog nooit heeft gezien. Kom er als eerste bij.', accesso: 'Toegang.', vetrina: 'In deze bouwfase is registratie vereist: binnen zie je de etalage van alle pvp.giustizia-veilingen — iCARe begeleidt je.', mille: 'De eerste 1.000: het eerste jaar gratis (alleen iShop-commissie en success fee).', piani: 'Plannen: Gold 12 maanden €59,90/maand · Gold maandelijks €69,90/maand.', world: 'iCARe World: voor 70+ en erkende beperking (L. 104/92) 50% korting en voorrang bij menselijke hulp.', reg: 'Registreren.', nome: 'Volledige naam', email: 'Email', cel: 'Mobiel (sms-bevestiging)', eta: 'Leeftijd', citta: 'Jouw stad', gusti: 'Jouw interesses', g1: 'Gerechtelijke veilingen', g2: 'Buy Now', g3: 'Modulair iHouse', g4: 'Meubels en iShop', g5: 'Investering', g6: 'Eerste huis', p1: 'Ik stem in met gegevensverwerking (AVG).', p2: 'Ik wil updates van de iUmana-revolutie.', btn: 'Word pionier', wallet: 'Registreer met Google, Apple of email: je wallet (Apple Pay / Google Pay) koppelt bij het afrekenen.', grazie: '✅ Welkom, pionier. Bevestig de geopende email.' },
    sv: { h1: 'Pionjärerna.', lead: 'Vi finslipar något världen aldrig har sett. Kom in före alla andra.', accesso: 'Tillträde.', vetrina: 'I byggfasen krävs registrering: inuti ser du skyltfönstret med alla pvp.giustizia-auktioner — iCARe guidar dig.', mille: 'De första 1.000: första året gratis (endast iShop-provision och success fee).', piani: 'Planer: Gold 12 mån €59,90/mån · Gold månadsvis €69,90/mån.', world: 'iCARe World: för 70+ och certifierad funktionsnedsättning (L. 104/92), 50 % rabatt och prioriterad hjälp.', reg: 'Registrera.', nome: 'Fullständigt namn', email: 'Email', cel: 'Mobil (SMS-bekräftelse)', eta: 'Ålder', citta: 'Din stad', gusti: 'Dina intressen', g1: 'Exekutiva auktioner', g2: 'Buy Now', g3: 'Modulärt iHouse', g4: 'Möbler och iShop', g5: 'Investering', g6: 'Första bostad', p1: 'Jag samtycker till databehandling (GDPR).', p2: 'Jag vill ha uppdateringar om iUmana-revolutionen.', btn: 'Bli pionjär', wallet: 'Registrera med Google, Apple eller email: din plånbok (Apple Pay / Google Pay) kopplas vid kassan.', grazie: '✅ Välkommen, pionjär. Bekräfta det öppnade mejlet.' },
  };
  var lang = 'it';
  function applica() {
    var t = T[lang] || T.it;
    var map = { 'titolo-page': t.h1, 'lead-page': t.lead, 'h2-accesso': t.accesso, 'vetrina-page': t.vetrina, 'mille-page': t.mille, 'piani-page': t.piani, 'world-page': t.world, 'h2-reg': t.reg, 'lb-nome': t.nome, 'lb-email': t.email, 'lb-cel': t.cel, 'lb-eta': t.eta, 'lb-citta': t.citta, 'lg-gusti': t.gusti, 'lb-g1': t.g1, 'lb-g2': t.g2, 'lb-g3': t.g3, 'lb-g4': t.g4, 'lb-g5': t.g5, 'lb-g6': t.g6, 'lb-p1': t.p1, 'lb-p2': t.p2, 'btn-pioniere': t.btn, 'nota-dopo': (t.nota || T.en.nota), 'wallet-note': t.wallet };
    Object.keys(map).forEach(function (id) { var el = document.getElementById(id); if (el) el.textContent = map[id]; });
    document.querySelectorAll('.lang-btn').forEach(function (b) { b.classList.toggle('lang-attivo', b.getAttribute('data-sel') === lang); });
  }
  document.querySelectorAll('.lang-btn').forEach(function (b) { b.addEventListener('click', function () { lang = b.getAttribute('data-sel'); applica(); }); });
  document.querySelectorAll('.intro-btns button').forEach(function (b) { b.addEventListener('click', function () { var el = document.getElementById(b.getAttribute('data-vai')); if (el) el.scrollIntoView({ behavior: 'smooth' }); }); });
  ['btn-google', 'btn-apple', 'btn-wallet'].forEach(function (id) { var b = document.getElementById(id); if (!b) return; b.addEventListener('click', function () { var e = document.getElementById('p-esito'); if (e) e.textContent = 'Collegamento in attivazione: completa il modulo (email) — Google, Apple e wallet si attivano con la release ufficiale.'; }); });
  var f = document.getElementById('forma-pioniere');
  if (f) {
    f.addEventListener('submit', function (ev) {
      ev.preventDefault();
      var V = function (id) { var x = document.getElementById(id); return x ? x.value.trim() : ''; };
      var nome = V('p-nome'), email = V('p-email'), cel = V('p-cel'), eta = V('p-eta'), citta = V('p-citta');
      var esito = document.getElementById('p-esito');
      if (!nome || !email || !cel) { esito.textContent = 'Campi obbligatori: ' + (T[lang] || T.it).nome + ', ' + (T[lang] || T.it).email + '. '; return; }
      if (!document.getElementById('p-privacy').checked) { esito.textContent = 'Serve il consenso privacy (GDPR).'; return; }
      var gusti = [];
      ['g-aste', 'g-buynow', 'g-ihouse', 'g-ishop', 'g-invest', 'g-primacasa'].forEach(function (id) { var x = document.getElementById(id); if (x && x.checked) gusti.push(id.slice(2)); });
      var news = document.getElementById('p-news').checked;
      var pioniere = { nome: nome, email: email, cellulare: cel, eta: eta, citta: citta, gusti: gusti, news: news, lingua: lang, data: new Date().toISOString() };
      try { var lista = JSON.parse(localStorage.getItem('icare-pionieri') || '[]'); lista.push(pioniere); localStorage.setItem('icare-pionieri', JSON.stringify(lista)); localStorage.setItem('icare-pioniere', '1'); } catch (err) {}
      var corpo = 'Nome: ' + nome + '\nEmail: ' + email + '\nCellulare: ' + cel + '\nEtà: ' + eta + '\nCittà: ' + citta + '\nGusti: ' + (gusti.join(', ') || '—') + '\nLingua: ' + lang + '\nAggiornamenti: ' + (news ? 'SI' : 'NO');
      window.location.href = 'mailto:info@puntoluce26.com?subject=' + encodeURIComponent('Nuovo pioniere — ' + nome) + '&body=' + encodeURIComponent(corpo);
      esito.textContent = (T[lang] || T.it).grazie;
    });
  }
  applica();
})();
